services:
  - type: web
    name: vidsnap-ai
    env: python
    region: oregon
    plan: free
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: cd backend && gunicorn -w 2 -b 0.0.0.0:$PORT main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "False"
      - key: ELEVENLABS_API_KEY
        sync: false
